# Config for Google Cloud Build
#
# Run with:
#   gcloud builds submit --config cloudbuild.yaml . \
#     --substitutions=_MC_VERSION=1.12.2

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/minecraft-vanilla:${_MC_VERSION}', '--build-arg', 'MC_VERSION=${_MC_VERSION}', '.']
    timeout: 500s
substitutions:
  _MC_VERSION: '1.12.2'
images:
  - 'gcr.io/$PROJECT_ID/minecraft-vanilla:${_MC_VERSION}'
